In [23]:
import numpy as np
import math

# Basic Array creation

In [51]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [25]:
a = [1,2,1.2,"hello"]
a


[1, 2, 1.2, 'hello']

In [26]:
np.array(a)

array(['1', '2', '1.2', 'hello'], dtype='<U32')

vector are one dimensional 
matrix are multi dimensional array

In [27]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.arange(0,11,4)

array([0, 4, 8])

In [29]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.__version__

'2.2.6'

In [32]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# random number generation

In [33]:
np.random.rand(5)

array([0.57902752, 0.21955214, 0.17090537, 0.25336888, 0.17264806])

In [35]:
for i in range(5):
    print(np.random.rand())


0.9789259389187668
0.27188713210538706
0.9508355565992479
0.9007476938611809
0.789682002860169


In [37]:
np.random.randn(10)

array([-0.24880706, -0.05433294,  1.57745459,  1.00970954,  0.86578306,
       -1.03989176, -1.09201033,  0.35908458, -0.62506142,  2.18097878])

In [ ]:
np.random.randint(10,20,10)


array([2])

In [49]:
np.random.randint(1,6,1)

array([2])

In [ ]:
arr.dtype



dtype('int64')